### PR TITLE
ref #63 adapted output of antiweb's daemon mode

### PR DESCRIPTION
**Pull request by lta14**
This change is [Reviewable](https://reviewable.io/reviews/7enderhead/antiweb/68)

### CODE REVIEW

**Comment by 7enderhead** [comment]
please rework

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[antiweb_lib/filechangehandler.py, line 91 at r1](https://reviewable.io:443/reviews/7enderhead/antiweb/68#-KalYwzIs_wuAaqUovPW:-KalYwzJ15Zc2NLpzDCo:b5bdudh) ([raw file](https://github.com/7enderhead/antiweb/blob/c6a2503629d9cc7922e0a3d45230368be109a458/antiweb_lib/filechangehandler.py#L91)):*
> ```Python
>                 #sys.exit is called when an input file cannot be opened/found
>                 #hence we catch the exception to let the daemon continue working
>                 event_string = "Catched SysExit: File: " + created_file + " could not be generated"
> ```

- 'Catched SysExist' -> 'Exception occurred'
- Can you get more detailed information from the exception?

---

*[antiweb_lib/write.py, line 185 at r1](https://reviewable.io:443/reviews/7enderhead/antiweb/68#-KalZmA4SZV3t5UkaR02:-KalZmA4SZV3t5UkaR03:bsl4168) ([raw file](https://github.com/7enderhead/antiweb/blob/c6a2503629d9cc7922e0a3d45230368be109a458/antiweb_lib/write.py#L185)):*
> ```Python
>    :param input_file: Contains the absolute path of the currently processed file.
>    :param options: Commandline options.
>    :return: a tuple of type <boolean, string>: the first value indicates if the documentation file could be generated and
> ```

- no fan of multiple return values if not absolutely necessary
- Why not return `None` as indication that file could not be generated?

---

*[antiweb_lib/write.py, line 280 at r1](https://reviewable.io:443/reviews/7enderhead/antiweb/68#-Kal_1Nr_kMZk7eCBgCE:-Kal_1Nr_kMZk7eCBgCF:bqgcf1v) ([raw file](https://github.com/7enderhead/antiweb/blob/c6a2503629d9cc7922e0a3d45230368be109a458/antiweb_lib/write.py#L280)):*
> ```Python
> 
> #@cstart(write_file)
> def write_file(working_dir, input_file, options):
> ```

- Extra method needed?
- Perhaps optional `print_message` (default false) parameter to existent `write`?

---

*[antiweb_lib/write.py, line 301 at r1](https://reviewable.io:443/reviews/7enderhead/antiweb/68#-Kal_Z1MkInBXYankCgM:-Kal_Z1MkInBXYankCgN:b-zgkrpi) ([raw file](https://github.com/7enderhead/antiweb/blob/c6a2503629d9cc7922e0a3d45230368be109a458/antiweb_lib/write.py#L301)):*
> ```Python
> 
> #@cstart(create_write_string)
> def create_write_string(could_write, input_file, created_file):
> ```

- Does this 'logic' warrant a separate method?
- Only used once in logging in antiweb.py -> move there completely?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/68#-:-Kal_r1f5xTxEEG0sSmr:byn8qmt)*

**Comment by lta14** [comment]
*[antiweb_lib/write.py, line 185 at r1](https://reviewable.io:443/reviews/7enderhead/antiweb/68#-KalZmA4SZV3t5UkaR02:-Kalkhw1OjQ-J_bQy5kq:biurp6q) ([raw file](https://github.com/7enderhead/antiweb/blob/c6a2503629d9cc7922e0a3d45230368be109a458/antiweb_lib/write.py#L185)):*
<details><summary><i>Previously, 7enderhead wrote…</i></summary><blockquote>

- no fan of multiple return values if not absolutely necessary
- Why not return `None` as indication that file could not be generated?
</blockquote></details>

You are right - no returning None or the absolute path of the created documentation file. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/68)*

**Comment by lta14** [comment]
*[antiweb_lib/write.py, line 280 at r1](https://reviewable.io:443/reviews/7enderhead/antiweb/68#-Kal_1Nr_kMZk7eCBgCE:-KallNOedqBnl-qZmH5V:b9tlxv5) ([raw file](https://github.com/7enderhead/antiweb/blob/c6a2503629d9cc7922e0a3d45230368be109a458/antiweb_lib/write.py#L280)):*
<details><summary><i>Previously, 7enderhead wrote…</i></summary><blockquote>

- Extra method needed?
- Perhaps optional `print_message` (default false) parameter to existent `write`?
</blockquote></details>

You are right. Removed this method and added a default parameter. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/68)*

**Comment by lta14** [comment]
*[antiweb_lib/write.py, line 301 at r1](https://reviewable.io:443/reviews/7enderhead/antiweb/68#-Kal_Z1MkInBXYankCgM:-Kalg5nuLdUFkIOKacaJ:b76bmuk) ([raw file](https://github.com/7enderhead/antiweb/blob/c6a2503629d9cc7922e0a3d45230368be109a458/antiweb_lib/write.py#L301)):*
<details><summary><i>Previously, 7enderhead wrote…</i></summary><blockquote>

- Does this 'logic' warrant a separate method?
- Only used once in logging in antiweb.py -> move there completely?
</blockquote></details>

Yes this logic warrant a seperate method as it is now used is in the method write() and in the Filechangehandler.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/68)*

**Comment by lta14** [comment]
*[antiweb_lib/filechangehandler.py, line 91 at r1](https://reviewable.io:443/reviews/7enderhead/antiweb/68#-KalYwzIs_wuAaqUovPW:-Kaus6_0Ypv0GJhqUNba:b647wsf) ([raw file](https://github.com/7enderhead/antiweb/blob/c6a2503629d9cc7922e0a3d45230368be109a458/antiweb_lib/filechangehandler.py#L91)):*
<details><summary><i>Previously, 7enderhead wrote…</i></summary><blockquote>

- 'Catched SysExist' -> 'Exception occurred'
- Can you get more detailed information from the exception?
</blockquote></details>

Removed the catch of SystemExit here as SysExit was thrown if an IO/Error occurred on the input file.
Now an IO exception is catched and None is returned.
A SysExit exception is also thrown if the documentation directory cannot be created - but this happens before the daemon has started.
Hence no need to catch a SysExit anymore. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/68)*

**Comment by 7enderhead** [comment]
:lgtm:

---

Reviewed 13 of 15 files at r2.
Review status: 13 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/68#-:-Kava-54wzfDFzaeTs-7:bnfp4nl)*

**Comment by 7enderhead** [comment]
Reviewed 2 of 15 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/68)*

**Pull request merged**
