### PR TITLE
Added antiweb daemon mode.

### PR DESCRIPTION
**Pull request by lta14**
This change is [Reviewable](https://reviewable.io/reviews/7enderhead/antiweb/61)

### CODE REVIEW

**Comment by 7enderhead** [comment]
Reviewed 9 of 43 files at r1.
Review status: 9 of 43 files reviewed at latest revision, 2 unresolved discussions.

---

*[antiweb_lib/filechangehandler.py, line 38 at r1](https://reviewable.io:443/reviews/7enderhead/antiweb/61#-Ka7vWAvNoweboUAYMUa:-Ka7vWAvNoweboUAYMUb:bmtj1bx) ([raw file](https://github.com/7enderhead/antiweb/blob/a46fb297989cbe420cc6756640f6a9667c3a47ef/antiweb_lib/filechangehandler.py#L38)):*
> ```Python
>     .. py:class:: FileChangeHandler(directory, extensions, options)
> 
>        This handler is responsible for handling changed file events on antiweb's daemon mode.
> ```

'in' antiweb's daemon mode

---

*[antiweb_lib/filechangehandler.py, line 74 at r1](https://reviewable.io:443/reviews/7enderhead/antiweb/61#-Ka7tmIiQGY_3whueKDx:-Ka7tmIjpIduwPWh86Xt:bwwczop) ([raw file](https://github.com/7enderhead/antiweb/blob/a46fb297989cbe420cc6756640f6a9667c3a47ef/antiweb_lib/filechangehandler.py#L74)):*
> ```Python
> 
>         if event.event_type == "moved":
>             #moved event has to be handled different:
> ```

'differently', 'in a different way'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/61)*

**Comment by 7enderhead** [comment]
Please perform small corrections.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/61#-:-KaCQMtIYKxF_fSGdbcb:b-wkipry)*

**Comment by 7enderhead** [comment]
:lgtm:

---

Reviewed 34 of 43 files at r1.
Review status: 42 of 43 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/61#-:-KaDCvPxb_GUb-5aaiiA:bnfp4nl)*

**Comment by 7enderhead** [comment]
:lgtm:

---

Reviewed 2 of 8 files at r2.
Review status: 39 of 45 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/61#-:-KaDDS53NmmCAYAsNwCH:bnfp4nl)*

**Comment by 7enderhead** [comment]
Reviewed 6 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/61)*

**Comment by lta14** [comment]
*[antiweb_lib/filechangehandler.py, line 74 at r1](https://reviewable.io:443/reviews/7enderhead/antiweb/61#-Ka7tmIiQGY_3whueKDx:-KaDDq8ZZ43UrCiDLqvp:b-896fix) ([raw file](https://github.com/7enderhead/antiweb/blob/a46fb297989cbe420cc6756640f6a9667c3a47ef/antiweb_lib/filechangehandler.py#L74)):*
<details><summary><i>Previously, 7enderhead wrote…</i></summary><blockquote>

'differently', 'in a different way'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/61)*

**Comment by lta14** [comment]
*[antiweb_lib/filechangehandler.py, line 38 at r1](https://reviewable.io:443/reviews/7enderhead/antiweb/61#-Ka7vWAvNoweboUAYMUa:-KaDDbdlWEsPimb23TIu:b-896fix) ([raw file](https://github.com/7enderhead/antiweb/blob/a46fb297989cbe420cc6756640f6a9667c3a47ef/antiweb_lib/filechangehandler.py#L38)):*
<details><summary><i>Previously, 7enderhead wrote…</i></summary><blockquote>

'in' antiweb's daemon mode
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/61)*

**Pull request merged**
