### PR TITLE
added class Document to antiweb_lib package

### PR DESCRIPTION
**Pull request by GhostPHX**
This change is [Reviewable](https://reviewable.io/reviews/7enderhead/antiweb/45)

### CODE REVIEW

**Comment by 7enderhead** [comment]
- please apply small corrections

---

Reviewed 39 of 39 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[antiweb.py, line 21 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/45#-KPmRhWqNs8H_Tq5A64K:-KPmRhWqNs8H_Tq5A64L:b-dc5vr6) ([raw file](https://github.com/7enderhead/antiweb/blob/db05cc9cf28a4836cdd85f9be57ce1e00a5cbece/antiweb.py#L21)):_

> ``` Python
> 
> ######
> antiweb
> ```

over-/underlining too short

---

_[antiweb.py, line 91 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/45#-KPmRqjHfJtZqP-psofy:-KPmRqjHfJtZqP-psofz:b-lm7scd) ([raw file](https://github.com/7enderhead/antiweb/blob/db05cc9cf28a4836cdd85f9be57ce1e00a5cbece/antiweb.py#L91)):_

> ``` Python
> and registering it in the readers dictionary (see readers).
> A simple Reader example is provides by :py:class:`CReader`
> a more advances reader is :py:class:`PythonReader`.
> ```

'advanced'

---

_[antiweb.py, line 244 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/45#-KPmSDojKVLzOEdCDfW7:-KPmSDok0rvXqZnQpiKW:b-tc580g) ([raw file](https://github.com/7enderhead/antiweb/blob/f79a587703c49f9cfc0de7024a25f75f855164f0/antiweb.py#L244)):_

> ``` Python
> __version__ = "0.3.3"
> 
> logger = logging.getLogger('antiweb')
> ```

I think we can leave this statement in any module that needs logging, since the logging system will return the same 'antiweb' logger

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/45#-:-KPmSfqB729hrb5ZOzDz:bbb8lyk)_

**Comment by 7enderhead** [comment]
:lgtm:

---

Reviewed 20 of 21 files at r2, 18 of 18 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[tests/data/unittest/docs/index_multiple.rst, line 1 [r2]](https://reviewable.io:443/reviews/7enderhead/antiweb/45#-KPqfcUxUS8FhXrbGlDr:-KPqfcUxUS8FhXrbGlDs:bjxcei8) ([raw file](https://github.com/7enderhead/antiweb/blob/5d0a5e8e25c6e2bc838b967432a5a54644d49442/tests/data/unittest/docs/index_multiple.rst#L1)):_

> ``` reStructuredText
> Documentation
> ```
- looks like a test file
- Should this be checked in?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/45#-:-KPqv4CumyPyDOzWCUjC:bg7igk9)_

**Comment by GhostPHX** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[tests/data/unittest/docs/index_multiple.rst, line 1 [r2]](https://reviewable.io:443/reviews/7enderhead/antiweb/45#-KPqfcUxUS8FhXrbGlDr:-KPqvexxOhSh9cXdXCR9:b-1967o0) ([raw file](https://github.com/7enderhead/antiweb/blob/5d0a5e8e25c6e2bc838b967432a5a54644d49442/tests/data/unittest/docs/index_multiple.rst#L1)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> - looks like a test file
> - Should this be checked in?
>   </details>
>   No, I will delete it (was related to index fix)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/45)_

**Comment by 7enderhead** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/45#-:-KPqxEhSEXhMB61hPV6t:bnfp4nl)_

**Pull request merged**
