### PR TITLE
ref #34 antiweb now uses working directory when no directory is given.

### PR DESCRIPTION
**Pull request by GhostPHX**
This change is [Reviewable](https://reviewable.io/reviews/7enderhead/antiweb/40)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/7enderhead/antiweb/pull/40" target="_blank">ReviewNinja

**Comment by 7enderhead** [comment]
Needs some rework.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[antiweb.py, line 3114 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/40#-KPMarhRukDnbqqmfZMJ:-KPMarhRukDnbqqmfZMK:bsk6iri) ([raw file](https://github.com/7enderhead/antiweb/blob/ed6749bc8ac99c51f1797cb1d70b258fe6cd5da1/antiweb.py#L3114)):_

> ``` Python
> #@(create_index_file)    
> 
> def parsing():
> ```

This function is poorly documented. Please add appropriate antiweb documentation, describing its functionality, especially the output parameters.

---

_[antiweb.py, line 3158 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/40#-KPMbArtlYy7x3di-9ue:-KPMbArtlYy7x3di-9uf:b-c2h9lt) ([raw file](https://github.com/7enderhead/antiweb/blob/ed6749bc8ac99c51f1797cb1d70b258fe6cd5da1/antiweb.py#L3158)):_

> ``` Python
>         argsExist = True
> 
>     return (options, args, parser, argsExist)
> ```
- you don't need the additional `argsExist` parameter
- you can easily test whether `args` has any values at the place where you inspect it

---

_[antiweb.py, line 3185 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/40#-KPMbp0CPTTf6sMDnoMC:-KPMbp0CPTTf6sMDnoMD:b885j8m) ([raw file](https://github.com/7enderhead/antiweb/blob/ed6749bc8ac99c51f1797cb1d70b258fe6cd5da1/antiweb.py#L3185)):_

> ``` Python
>     previous_dir = os.getcwd()
> 
>     #Convert to absolute path. This is needed if a relative path was given.
> ```

This logic needs more documentation regarding what happens if no path was given

---

_[antiweb.py, line 3189 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/40#-KPMb_qKQQcKqjbmm7fp:-KPMb_qKQQcKqjbmm7fq:b-nj78e) ([raw file](https://github.com/7enderhead/antiweb/blob/ed6749bc8ac99c51f1797cb1d70b258fe6cd5da1/antiweb.py#L3189)):_

> ``` Python
>         absolute_path = os.path.abspath(args[0])
>     else:
>         absolute_path = os.path.abspath(args)
> ```
- I don't understand the logic here
- Why do you convert a non-existent argument to an absolute path?
- What is the return value then?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/40#-:-KPMcGuWu4YS5RuuUjCC:b-asnwe2)_

**Comment by GhostPHX** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[antiweb.py, line 3158 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/40#-KPMbArtlYy7x3di-9ue:-KPMgzDj5KIakZxLmxIn:b-pvqtoc) ([raw file](https://github.com/7enderhead/antiweb/blob/ed6749bc8ac99c51f1797cb1d70b258fe6cd5da1/antiweb.py#L3158)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> - you don't need the additional `argsExist` parameter
> - you can easily test whether `args` has any values at the place where you inspect it
>   </details>
>   I fixed the problem I had here by setting args as an array (was previously set as variable when no input was given). I previously had to differentiate between array and variable

---

_[antiweb.py, line 3189 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/40#-KPMb_qKQQcKqjbmm7fp:-KPMjI1GAn1-ZYtMXpxf:bdmel2g) ([raw file](https://github.com/7enderhead/antiweb/blob/ed6749bc8ac99c51f1797cb1d70b258fe6cd5da1/antiweb.py#L3189)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> - I don't understand the logic here
> - Why do you convert a non-existent argument to an absolute path?
> - What is the return value then?
>   </details>
>   The user input (respectively the input I set when none is given) can be relative, so we grab the absolute path to work with. In addition, the earlier removal of ArgsExist gets rid of this snippet and just leaves absolute_path = os.path.abspath(args[0])

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/40)_

**Comment by 7enderhead** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[antiweb.py, line 3158 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/40#-KPMbArtlYy7x3di-9ue:-KPMlDYEApk5nBpNSmP_:baq38kb) ([raw file](https://github.com/7enderhead/antiweb/blob/ed6749bc8ac99c51f1797cb1d70b258fe6cd5da1/antiweb.py#L3158)):_
<details><summary>

<i>Previously, Yarmek (Philipp) wrote…</i></summary>



> I fixed the problem I had here by setting args as an array (was previously set as variable when no input was given). I previously had to differentiate between array and variable
> </details>
> Ok, commit the change.

---

_[antiweb.py, line 3189 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/40#-KPMb_qKQQcKqjbmm7fp:-KPMlFQvYfu2hB0ckit9:b-56lk4z) ([raw file](https://github.com/7enderhead/antiweb/blob/ed6749bc8ac99c51f1797cb1d70b258fe6cd5da1/antiweb.py#L3189)):_
<details><summary>

<i>Previously, Yarmek (Philipp) wrote…</i></summary>



> The user input (respectively the input I set when none is given) can be relative, so we grab the absolute path to work with. In addition, the earlier removal of ArgsExist gets rid of this snippet and just leaves absolute_path = os.path.abspath(args[0])
> </details>
> I need this as documentation in antiweb itself. (Minus the mentioning of already deleted code.)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/40)_

**Comment by GhostPHX** [comment]
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

_[antiweb.py, line 3114 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/40#-KPMarhRukDnbqqmfZMJ:-KPN2bh6cFk9S3N2YTgq:b9w6xan) ([raw file](https://github.com/7enderhead/antiweb/blob/ed6749bc8ac99c51f1797cb1d70b258fe6cd5da1/antiweb.py#L3114)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> This function is poorly documented. Please add appropriate antiweb documentation, describing its functionality, especially the output parameters.
> </details>
> Added documentation for that function

---

_[antiweb.py, line 3158 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/40#-KPMbArtlYy7x3di-9ue:-KPN2RnbQnMW-5igbQ38:b-896fix) ([raw file](https://github.com/7enderhead/antiweb/blob/ed6749bc8ac99c51f1797cb1d70b258fe6cd5da1/antiweb.py#L3158)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> Ok, commit the change.
> </details>
> Done.

---

_[antiweb.py, line 3185 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/40#-KPMbp0CPTTf6sMDnoMC:-KPN27kVyge18Lyyb5Zt:bg3m8wx) ([raw file](https://github.com/7enderhead/antiweb/blob/ed6749bc8ac99c51f1797cb1d70b258fe6cd5da1/antiweb.py#L3185)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> This logic needs more documentation regarding what happens if no path was given
> </details>
> Added better documentation for that case

---

_[antiweb.py, line 3189 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/40#-KPMb_qKQQcKqjbmm7fp:-KPN20bCI6efI0vNbdXU:b-3xifgj) ([raw file](https://github.com/7enderhead/antiweb/blob/ed6749bc8ac99c51f1797cb1d70b258fe6cd5da1/antiweb.py#L3189)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> I need this as documentation in antiweb itself. (Minus the mentioning of already deleted code.)
> </details>
> Added to documentation in antiweb

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/40)_

**Comment by 7enderhead** [comment]
Documentation still not up to date.

---

Reviewed 28 of 28 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[documentation/source/antiweb.rst, line 1817 [r3]](https://reviewable.io:443/reviews/7enderhead/antiweb/40#-KPSCbds6sW9KVKJBRPk:-KPSCbdtp7jOP2NWBJ1i:bg0cik5) ([raw file](https://github.com/7enderhead/antiweb/blob/3a667fe4f2a1fc4b172d767b44332901e84e9d66/documentation/source/antiweb.rst#L1817)):_

> ``` reStructuredText
>               self.lines = self.reader.process(fname, text)
>               if not self.lines:
>                   self.lines = [Line(1, 0, ())]
> ```

This doesn't reflect the latest code.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/40#-:-KPSCuDaPT1bIoItqSAw:bqh5dcg)_

**Comment by 7enderhead** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/40#-:-KPSX4Z6Fu9mBCth0idR:bnfp4nl)_

**Comment by 7enderhead** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[documentation/source/antiweb.rst, line 1817 [r3]](https://reviewable.io:443/reviews/7enderhead/antiweb/40#-KPSCbds6sW9KVKJBRPk:-KPSXUeOkljWmCmnICVL:b32w0x) ([raw file](https://github.com/7enderhead/antiweb/blob/3a667fe4f2a1fc4b172d767b44332901e84e9d66/documentation/source/antiweb.rst#L1817)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> This doesn't reflect the latest code.
> </details>
> OK

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/40)_

**Pull request merged**
