### PR TITLE
ref #41 antiweb can now handle empty files

### PR DESCRIPTION
**Pull request by GhostPHX**
This change is [Reviewable](https://reviewable.io/reviews/7enderhead/antiweb/42)

### CODE REVIEW

**Comment by 7enderhead** [comment]
Small corrections to be made

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[antiweb.py, line 2412 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/42#-KPWNEQkzETeKQKAau0X:-KPWNEQkzETeKQKAau0Y:bgigm3v) ([raw file](https://github.com/7enderhead/antiweb/blob/c99c4627a2e405f8e1297fcc430aa0acddf98baf/antiweb.py#L2412)):_

> ``` Python
>         self.collect_blocks()
> 
>         #check if there are any lines in the file and add the according error message
> ```

Please use whitespace after comment character

---

_[antiweb.py, line 2509 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/42#-KPWMOVNPWxGQP4D5b6q:-KPWMOVOXYpvigMkr8kT:b-im78kh) ([raw file](https://github.com/7enderhead/antiweb/blob/c99c4627a2e405f8e1297fcc430aa0acddf98baf/antiweb.py#L2509)):_

> ``` Python
>            :param integer line_number: The line number that causes the error.
>            :param string text: An error text.
>            :param string fname: Optionally add the filename
> ```

'name of currently processed file (needed if no data in self.lines)' 

---

_[antiweb.py, line 2512 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/42#-KPWMWU-qLDxHLur79y4:-KPWMWU-qLDxHLur79y5:b8u5jx8) ([raw file](https://github.com/7enderhead/antiweb/blob/c99c4627a2e405f8e1297fcc430aa0acddf98baf/antiweb.py#L2512)):_

> ``` Python
> 
>         """
>         #determine if the file is empty
> ```
- Actually, we determine whether the access via index `line_number` is possible
- Please use whitespace after comment character

---

_[antiweb.py, line 2516 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/42#-KPWMooJt-f2Wbd62knH:-KPWMooJt-f2Wbd62knI:b-zdumbj) ([raw file](https://github.com/7enderhead/antiweb/blob/c99c4627a2e405f8e1297fcc430aa0acddf98baf/antiweb.py#L2516)):_

> ``` Python
>             line = self.lines[line_number]
>         else:
>             line = Line(fname, -1, "")
> ```

Document why we add the 'fake' line

---

_[tests/test_antiweb.py, line 245 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/42#-KPWNOnnzyyVwHySAbwC:-KPWNOnnzyyVwHySAbwD:be52xvm) ([raw file](https://github.com/7enderhead/antiweb/blob/c99c4627a2e405f8e1297fcc430aa0acddf98baf/tests/test_antiweb.py#L245)):_

> ``` Python
>         os.chdir(previ_dir)
> 
>     #First goal: antiweb should not crash on this empty file; Second Goal: antiweb should not create any files
> ```
- Please use whitespace after comment character
- Separate goals into two comment lines

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/42#-:-KPWNbgSWRaezhgeaMKb:bmfxzjq)_

**Comment by GhostPHX** [comment]
commited

---

Review status: 14 of 16 files reviewed at latest revision, 5 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/42#-:-KPWSaSYULTW73YxFZin:bq8d3q3)_

**Comment by 7enderhead** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[antiweb.py, line 2517 [r2]](https://reviewable.io:443/reviews/7enderhead/antiweb/42#-KPWUoWpjz4v7W7AN8cv:-KPWUoWpjz4v7W7AN8cw:biam1q0) ([raw file](https://github.com/7enderhead/antiweb/blob/ee18c956a7ff7e7acbb1b674429b06ff6dbcfca5/antiweb.py#L2517)):_

> ``` Python
>         else:
>             # without a line in self.lines, antiweb would crash on appending it to the errors (errorlist)
>             # antiweb adds a 'fake line' to preserve that issue
> ```
- replace 'antiweb' with 'we'
- 'preserver' -> 'prevent'

---

_[tests/test_antiweb.py, line 245 [r2]](https://reviewable.io:443/reviews/7enderhead/antiweb/42#-KPWVvUVP2QX0GRAlkDp:-KPWVvUWX3ww4MJVh3yE:bxdb4qb) ([raw file](https://github.com/7enderhead/antiweb/blob/ee18c956a7ff7e7acbb1b674429b06ff6dbcfca5/tests/test_antiweb.py#L245)):_

> ``` Python
>         os.chdir(previ_dir)
> 
>     # First goal: antiweb should not crash on this empty file; 
> ```

Simply 'don't crash' (avoid usage of 'antiweb' in comments)

---

_[tests/test_antiweb.py, line 246 [r2]](https://reviewable.io:443/reviews/7enderhead/antiweb/42#-KPWW0K05yue61k3WcCe:-KPWW0K05yue61k3WcCf:b-st9wc8) ([raw file](https://github.com/7enderhead/antiweb/blob/ee18c956a7ff7e7acbb1b674429b06ff6dbcfca5/tests/test_antiweb.py#L246)):_

> ``` Python
> 
>     # First goal: antiweb should not crash on this empty file; 
>     # Second Goal: antiweb should not create any files
> ```

See previous comment

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/42)_

**Comment by GhostPHX** [comment]
Done + also removed two unnecessary lines (2 variables assigned but never used)

---

Review status: 14 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/42#-:-KPWY21rKI-Yj5pmz-oz:b6on29o)_

**Comment by 7enderhead** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[antiweb.py, line 2517 [r3]](https://reviewable.io:443/reviews/7enderhead/antiweb/42#-KPW_c8Bs2UDztkzioNh:-KPW_c8Bs2UDztkzioNi:b-s0afd6) ([raw file](https://github.com/7enderhead/antiweb/blob/5fb5cd4e0f6bd1a5a5f9b41b4dde726e5bdcf7a0/antiweb.py#L2517)):_

> ``` Python
>         else:
>             # without a line in self.lines, antiweb would crash on appending it to the errors (errorlist)
>             # we a 'fake line' to prevent that issue
> ```

'we add'

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/42)_

**Comment by 7enderhead** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/42#-:-KPWdeF6X4uRC8kJF4Pp:bnfp4nl)_

**Pull request merged**
