### PR TITLE
ref #21 and #27 , added readers sub-package

### PR DESCRIPTION
**Pull request by GhostPHX**
This change is [Reviewable](https://reviewable.io/reviews/7enderhead/antiweb/44)

### CODE REVIEW

**Comment by 7enderhead** [comment]
- Please perform minor adjustments

---

Reviewed 42 of 42 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[.travis.yml, line 3 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/44#-KPlIOUsHF9WQ-t_RqAt:-KPlIOUsHF9WQ-t_RqAu:blixvvw) ([raw file](https://github.com/7enderhead/antiweb/blob/42fd6ba2c6b21edc91608e19db44c6be0fac338a/.travis.yml#L3)):_

> ``` YAML
> language: python
> os: 
>   - linux
> ```
- Why is that?
- Please add documentation for this file
  - inline here
  - in the overall docs

---

_[.travis.yml, line 5 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/44#-KPlIYLejOS_zpJ__iwg:-KPlIYLf4O0XDq7jj6O9:bcmhxx7) ([raw file](https://github.com/7enderhead/antiweb/blob/42fd6ba2c6b21edc91608e19db44c6be0fac338a/.travis.yml#L5)):_

> ``` YAML
>   - linux
> python:
>   - "3.4"
> ```
- Why do we need that?

---

_[antiweb_lib/readers/Reader.py, line 194 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/44#-KPlKM72Ji4IlP6R7rD_:-KPlKM73pMtv7cNTmYKo:b-akqpwt) ([raw file](https://github.com/7enderhead/antiweb/blob/42fd6ba2c6b21edc91608e19db44c6be0fac338a/antiweb_lib/readers/Reader.py#L194)):_

> ``` Python
> 
> #@cstart(Line)
> class Line(object):
> ```

Please put into separate file.

---

_[antiweb_lib/readers/rstReader.py, line 6 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/44#-KPlL30CnrV1hAnCt47P:-KPlL30CnrV1hAnCt47Q:b8wtpqa) ([raw file](https://github.com/7enderhead/antiweb/blob/42fd6ba2c6b21edc91608e19db44c6be0fac338a/antiweb_lib/readers/rstReader.py#L6)):_

> ``` Python
> 
> #@cstart(rstReader)
> class rstReader(Reader):
> ```
- I think the naming scheme is to use uppercase first letters
- Please rename to RstReader

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/44#-:-KPlLTJdhFLmdICg39nt:b6218ce)_

**Comment by GhostPHX** [comment]
Adjustments will be applied in the next commit

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[.travis.yml, line 3 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/44#-KPlIOUsHF9WQ-t_RqAt:-KPlLbuBFUM9QATd8vyx:bywjm5z) ([raw file](https://github.com/7enderhead/antiweb/blob/42fd6ba2c6b21edc91608e19db44c6be0fac338a/.travis.yml#L3)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> - Why is that?
> - Please add documentation for this file
>   - inline here
>   - in the overall docs
>     </details>
>     If we would like to add another operating system to our travis tests in the near future, we just have to add the os here (for convenience)

---

_[.travis.yml, line 5 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/44#-KPlIYLejOS_zpJ__iwg:-KPlM1qx6ypvRvokP82x:b6p9mvp) ([raw file](https://github.com/7enderhead/antiweb/blob/42fd6ba2c6b21edc91608e19db44c6be0fac338a/.travis.yml#L5)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> - Why do we need that?
>   </details>
>   We tell Travis, which versions of Python to use. Some dependencies are not compatible with Python versions below 3.4.

---

_[antiweb_lib/readers/Reader.py, line 194 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/44#-KPlKM72Ji4IlP6R7rD_:-KPlO13UuA5Va7T2IdEF:b-xwa1z1) ([raw file](https://github.com/7enderhead/antiweb/blob/42fd6ba2c6b21edc91608e19db44c6be0fac338a/antiweb_lib/readers/Reader.py#L194)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> Please put into separate file.
> </details>
> Done with next commit

---

_[antiweb_lib/readers/rstReader.py, line 6 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/44#-KPlL30CnrV1hAnCt47P:-KPlO4ouGFX3WJlsML7H:b-9ytnxa) ([raw file](https://github.com/7enderhead/antiweb/blob/42fd6ba2c6b21edc91608e19db44c6be0fac338a/antiweb_lib/readers/rstReader.py#L6)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> - I think the naming scheme is to use uppercase first letters
> - Please rename to RstReader
>   </details>
>   Done in next commit

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/44#-:-KPlOG2AZAOMmnz3OMne:b-u9mm39)_

**Comment by 7enderhead** [comment]
Please correct minor typo

---

Reviewed 41 of 44 files at r2, 2 of 2 files at r3.
Review status: 53 of 54 files reviewed at latest revision, 1 unresolved discussion.

---

_[documentation/source/travis.rst, line 9 [r3]](https://reviewable.io:443/reviews/7enderhead/antiweb/44#-KPm-VldpIHFDT0QMxcx:-KPm-VleWrMGi-KnLVYI:byczm3s) ([raw file](https://github.com/7enderhead/antiweb/blob/af0946f4fe0585f823a0d39d8de4a216bc68aa8e/documentation/source/travis.rst#L9)):_

> ``` reStructuredText
> ******************
> 
> This file tells our external website for continous integration, Travis-CI, how to peform the tests.
> ```

'perform'

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/44#-:-KPm-cMxazoIlitSBGNv:b-vtejii)_

**Comment by 7enderhead** [comment]
Reviewed 1 of 44 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/44)_

**Comment by 7enderhead** [comment]
:lgtm:

---

Reviewed 17 of 17 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/44#-:-KPm4c2yTRc4G84W7o-A:bnfp4nl)_

**Pull request merged**
