### PR TITLE
updated readme.md

### PR DESCRIPTION
**Pull request by GhostPHX**
This change is [Reviewable](https://reviewable.io/reviews/7enderhead/antiweb/35)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/7enderhead/antiweb/pull/35" target="_blank">ReviewNinja

**Comment by 7enderhead** [comment]
:lgtm:
(Looks Good to Me)

Consider minor issues in further iterations.

---

Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[.travis.yml, line 4 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOySxUuMGtsY1N04VSs:-KOySxUvgb6Un67wDzdH:bau4tnu) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/.travis.yml#L4)):_

> ``` YAML
> python:
>   - "3.4"
>   - "3.5"
> ```

Why do we need two python versions here?

---

_[antiweb.py, line 5 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOyTB9lAdNqE_BW9jHD:-KOyTB9lAdNqE_BW9jHE:bbxkz80) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/antiweb.py#L5)):_

> ``` Python
> """
> Name: antiweb
> Version: 0.3.2
> ```

Aren't we on 0.3.3 already?

---

_[antiweb.py, line 9 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOyU-AN4xJs7fv_6yEU:-KOyU-AN4xJs7fv_6yEV:b7whdwo) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/antiweb.py#L9)):_

> ``` Python
> Home-page: http://packages.python.org/antiweb/
> Author: Michael Reithinger, Philipp Rathmanner, Lukas Tanner, Philipp Grandits, Christian Eitner
> Author-email: mreithinger@web.de
> ```

Please change all contact mail addresses to 'antiweb@freelists.org'. I don't think M. Reithinger wants to be contacted about antiweb anymore.

---

_[PKG-INFO, line 7 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOyUHffWW-aTjYNN5UI:-KOyUHffWW-aTjYNN5UJ:bkavl3s) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/PKG-INFO#L7)):_

> ```
> Home-page: http://packages.python.org/antiweb/
> Author: Michael Reithinger, Philipp Rathmanner, Lukas Tanner, Philipp Grandits, Christian Eitner
> Author-email: mreithinger@web.de
> ```

See previous comment about mail address.

---

_[README.md, line 11 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOyULSz886VLBD--uQ6:-KOyULSz886VLBD--uQ7:bkavl3s) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/README.md#L11)):_

> ``` Markdown
> Author: Michael Reithinger, Philipp Rathmanner, Lukas Tanner, Philipp Grandits, Christian Eitner
> 
> Author-email: mreithinger@web.de
> ```

See previous comment about mail address.

---

_[setup.py, line 20 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOyUST5OffKtVr6U49c:-KOyUST5OffKtVr6U49d:bkavl3s) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/setup.py#L20)):_

> ``` Python
>     license='GPL',
>     author='Michael Reithinger, Philipp Rathmanner, Lukas Tanner, Philipp Grandits, Christian Eitner',
>     author_email='mreithinger@web.de & yarmek@icloud.com',
> ```

See previous comment about mail address.

---

_[documentation/source/installation.rst, line 12 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOyUfU_qt27qNBtXv5N:-KOyUfU_qt27qNBtXv5O:btn4hyp) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/documentation/source/installation.rst#L12)):_

> ``` reStructuredText
> ############
> 
> The most important parts of the system are Python 3, antiweb and Sphinx. (it will be automatically installed with antiweb). Because of incompatibility with Python 2 you can't create 
> ```

(It [...])

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-:-KOyV1VS_5_Zz1e_ou3A:bq8nksp)_

**Comment by 7enderhead** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[.travis.yml, line 4 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOySxUuMGtsY1N04VSs:-KOyVxCLEIZmVzkFugeL:b32w0x) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/.travis.yml#L4)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> Why do we need two python versions here?
> </details>
> OK

---

_[antiweb.py, line 5 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOyTB9lAdNqE_BW9jHD:-KOyW-ThwMgTxxtP4zOX:b32w0x) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/antiweb.py#L5)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> Aren't we on 0.3.3 already?
> </details>
> OK

---

_[antiweb.py, line 9 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOyU-AN4xJs7fv_6yEU:-KOyW0bylb_Ums19o_3y:b32w0x) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/antiweb.py#L9)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> Please change all contact mail addresses to 'antiweb@freelists.org'. I don't think M. Reithinger wants to be contacted about antiweb anymore.
> </details>
> OK

---

_[PKG-INFO, line 7 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOyUHffWW-aTjYNN5UI:-KOyW1gkNV81XYt4Bg0i:b32w0x) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/PKG-INFO#L7)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> See previous comment about mail address.
> </details>
> OK

---

_[README.md, line 11 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOyULSz886VLBD--uQ6:-KOyW2Yf3Dzzp0XXpxTy:b32w0x) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/README.md#L11)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> See previous comment about mail address.
> </details>
> OK

---

_[setup.py, line 20 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOyUST5OffKtVr6U49c:-KOyW3SdoxHQoKMm5sDn:b32w0x) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/setup.py#L20)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> See previous comment about mail address.
> </details>
> OK

---

_[documentation/source/installation.rst, line 12 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOyUfU_qt27qNBtXv5N:-KOyW4VxFWdmvv07YcBB:b32w0x) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/documentation/source/installation.rst#L12)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> (It [...])
> </details>
> OK

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/35)_

**Comment by 7enderhead** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[.travis.yml, line 4 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOySxUuMGtsY1N04VSs:-KOyWCswufj6JX3-xy-n:b2nhei9) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/.travis.yml#L4)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> OK
> </details>
> FYI

---

_[antiweb.py, line 5 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOyTB9lAdNqE_BW9jHD:-KOyWGea5-iQ-sPw8VVU:b2nhei9) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/antiweb.py#L5)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> OK
> </details>
> FYI

---

_[antiweb.py, line 9 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOyU-AN4xJs7fv_6yEU:-KOyWHAPMj-nuNF7uQbX:b2nhei9) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/antiweb.py#L9)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> OK
> </details>
> FYI

---

_[PKG-INFO, line 7 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOyUHffWW-aTjYNN5UI:-KOyWHlvGmqSQIg4-tIS:b2nhei9) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/PKG-INFO#L7)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> OK
> </details>
> FYI

---

_[README.md, line 11 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOyULSz886VLBD--uQ6:-KOyWJChBsauRWVS2s8o:b2nhei9) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/README.md#L11)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> OK
> </details>
> FYI

---

_[setup.py, line 20 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOyUST5OffKtVr6U49c:-KOyWIX_nS2RWKdUQY6Q:b2nhei9) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/setup.py#L20)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> OK
> </details>
> FYI

---

_[documentation/source/installation.rst, line 12 [r1]](https://reviewable.io:443/reviews/7enderhead/antiweb/35#-KOyUfU_qt27qNBtXv5N:-KOyWKOncxE-tF5OOHcc:b2nhei9) ([raw file](https://github.com/7enderhead/antiweb/blob/82402a5cdf18ae88a831fa529ec9fad72351dda1/documentation/source/installation.rst#L12)):_
<details><summary>

<i>Previously, 7enderhead wrote…</i></summary>



> OK
> </details>
> FYI

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/7enderhead/antiweb/35)_

**Pull request merged**
